"""Windows auto-start via the per-user Startup folder.

We previously used Task Scheduler (`schtasks /create`), but in many corporate
or Group-Policy-restricted environments `schtasks /create` returns
`ERROR_ACCESS_DENIED` even for a per-user logon task. The Startup folder
approach has no such restriction: dropping a `.vbs` shim into
`%APPDATA%\\Microsoft\\Windows\\Start Menu\\Programs\\Startup\\` is honored
on the next logon and works without admin rights or special policy.

The shim is a tiny `.vbs` that uses `WScript.Shell.Run(..., 0, False)` to
launch the helper completely hidden (no console window flash). stdout /
stderr are redirected to a log file so the user can inspect what the
backgrounded helper is doing.
"""

from __future__ import annotations

import os
import shutil
import subprocess
from pathlib import Path

SHIM_NAME = "HapbeatHelper.vbs"
LEGACY_TASK_NAME = "HapbeatHelper"  # for one-time cleanup of older installs


def _startup_dir() -> Path:
    appdata = os.environ.get("APPDATA")
    if not appdata:
        raise RuntimeError("APPDATA environment variable is not set")
    return Path(appdata) / "Microsoft" / "Windows" / "Start Menu" / "Programs" / "Startup"


def _shim_path() -> Path:
    return _startup_dir() / SHIM_NAME


def log_path() -> Path:
    """Where the auto-started helper's stdout/stderr are written."""
    local = os.environ.get("LOCALAPPDATA")
    base = Path(local) if local else Path.home() / "AppData" / "Local"
    return base / "hapbeat-helper" / "hapbeat-helper.log"


def _hapbeat_helper_path() -> str:
    path = shutil.which("hapbeat-helper")
    if not path:
        raise RuntimeError(
            "hapbeat-helper is not on PATH. "
            "Install via pipx: pipx install hapbeat-helper"
        )
    return str(Path(path).resolve())


def _build_vbs(exe: str, log: Path) -> str:
    # WScript.Shell.Run(strCommand, intWindowStyle, bWaitOnReturn)
    #   intWindowStyle=0 -> hidden, bWaitOnReturn=False -> non-blocking
    # We wrap the helper invocation in `cmd /c` so we can redirect stdout/
    # stderr to a log file. VBS string literal: inner double-quotes are
    # escaped by doubling them.
    cmd = (
        f'cmd /c """{exe}"" start >> ""{log}"" 2>&1'
    )
    return (
        "' Auto-generated by `hapbeat-helper install-service`.\r\n"
        "' Launches hapbeat-helper hidden at user logon and writes\r\n"
        f"' stdout/stderr to: {log}\r\n"
        "Set sh = CreateObject(\"WScript.Shell\")\r\n"
        f"sh.Run \"{cmd}\", 0, False\r\n"
    )


def _cleanup_legacy_task() -> None:
    """Best-effort removal of an old Task Scheduler entry from prior versions."""
    subprocess.run(
        ["schtasks", "/delete", "/tn", LEGACY_TASK_NAME, "/f"],
        capture_output=True,
    )


def _running_pids() -> list[int]:
    """PIDs of python.exe processes launched as hapbeat-helper."""
    try:
        out = subprocess.run(
            [
                "powershell.exe",
                "-NoProfile",
                "-Command",
                "Get-CimInstance Win32_Process -Filter \"Name='python.exe' OR Name='pythonw.exe'\" "
                "| Where-Object { $_.CommandLine -match 'hapbeat[-_]helper' } "
                "| Select-Object -ExpandProperty ProcessId",
            ],
            capture_output=True,
            text=True,
            timeout=10,
        )
    except (subprocess.TimeoutExpired, FileNotFoundError):
        return []
    if out.returncode != 0 or not out.stdout.strip():
        return []
    pids: list[int] = []
    for line in out.stdout.splitlines():
        line = line.strip()
        if line.isdigit():
            pids.append(int(line))
    return pids


def install() -> None:
    exe = _hapbeat_helper_path()
    log = log_path()
    log.parent.mkdir(parents=True, exist_ok=True)
    startup = _startup_dir()
    startup.mkdir(parents=True, exist_ok=True)
    shim = _shim_path()
    shim.write_text(_build_vbs(exe, log), encoding="utf-8")

    _cleanup_legacy_task()

    # Launch immediately so the user doesn't have to log out / back in.
    subprocess.Popen(
        ["wscript.exe", str(shim)],
        stdout=subprocess.DEVNULL,
        stderr=subprocess.DEVNULL,
    )
    print("hapbeat-helper auto-start installed.")
    print(f"  shim: {shim}")
    print(f"  exe:  {exe}")
    print(f"  log:  {log}")
    print("  next logon: Helper starts automatically (hidden).")


def uninstall() -> None:
    shim = _shim_path()
    if shim.exists():
        shim.unlink()
        print(f"removed: {shim}")
    else:
        print(f"not installed (no shim at {shim})")
    _cleanup_legacy_task()

    # Stop the currently-running instance so the user doesn't have to hunt
    # python.exe in Task Manager.
    pids = _running_pids()
    for pid in pids:
        subprocess.run(
            ["taskkill", "/F", "/PID", str(pid)], capture_output=True
        )
    if pids:
        print(f"stopped running helper (pid={','.join(str(p) for p in pids)})")
    print("hapbeat-helper auto-start removed.")


def stop() -> None:
    """Kill any running auto-started instance (without removing the shim)."""
    pids = _running_pids()
    if not pids:
        print("hapbeat-helper is not running.")
        return
    for pid in pids:
        subprocess.run(["taskkill", "/F", "/PID", str(pid)], capture_output=True)
    print(f"hapbeat-helper stopped (pid={','.join(str(p) for p in pids)}).")


def status() -> str:
    """Return one of: 'not_registered', 'stopped', 'running'."""
    if not _shim_path().exists():
        return "not_registered"
    return "running" if _running_pids() else "stopped"
