"""Generate src/hapbeat_helper/_version.py from git state.

Format:
  - On a release tag commit (HEAD == v0.1.2):  __version__ = "0.1.2"
  - On a dev commit:                            __version__ = "0.1.2d<N>"
        where <N> = number of commits since the most recent v* tag

The base version ("0.1.2") is read from pyproject.toml [project] version.
After cutting a release, bump that field once to the next intended version
(e.g. "0.1.3") and let the dev counter advance automatically.

_version.py is gitignored — it is never committed.
In production PyPI installs it doesn't exist; __init__.py falls back to
the hardcoded release version string.

Usage:
    python scripts/gen_version.py          # write _version.py
    python scripts/gen_version.py --print  # print version only, no file write
"""

from __future__ import annotations

import argparse
import re
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "src" / "hapbeat_helper" / "_version.py"


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _run_git(*args: str) -> str | None:
    try:
        out = subprocess.check_output(
            ["git", *args], cwd=ROOT, stderr=subprocess.DEVNULL
        )
        return out.decode("utf-8", errors="replace").strip()
    except (subprocess.CalledProcessError, FileNotFoundError):
        return None


def _read_base_version() -> str:
    """Read NEXT_RELEASE_VERSION from pyproject.toml [project] version."""
    text = (ROOT / "pyproject.toml").read_text(encoding="utf-8")
    m = re.search(r'^\s*version\s*=\s*"([^"]+)"', text, re.MULTILINE)
    if not m:
        raise SystemExit("ERROR: version field not found in pyproject.toml")
    return m.group(1)


def _compute_version(base: str) -> tuple[str, str]:
    """Return (version_string, source_description)."""
    # Exact tag match → release build.
    exact = _run_git("describe", "--tags", "--exact-match", "--match", "v*")
    if exact:
        return exact.lstrip("v"), f"tag-exact ({exact})"

    # Count commits since the last v* tag.
    last_tag = _run_git("describe", "--tags", "--abbrev=0", "--match", "v*")
    if last_tag:
        count_str = _run_git("rev-list", "--count", f"{last_tag}..HEAD")
        try:
            n = int(count_str or "0")
        except ValueError:
            n = 0
        if n == 0:
            return base, f"no commits since {last_tag}"
        return f"{base}d{n}", f"{n} commits since {last_tag}"

    # No tag at all → use total commit count.
    total = _run_git("rev-list", "--count", "HEAD")
    try:
        n = int(total or "0")
    except ValueError:
        n = 0
    return f"{base}d{n}", "no tags found; used total commit count"


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main(argv: list[str] | None = None) -> None:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--print", action="store_true", help="print only, do not write file")
    args = parser.parse_args(argv)

    base = _read_base_version()
    version, source = _compute_version(base)

    print(f"gen_version: {version}  ({source})")

    if args.print:
        return

    OUT.write_text(
        "# Auto-generated by scripts/gen_version.py — do not commit or edit.\n"
        f'__version__ = "{version}"\n',
        encoding="utf-8",
    )
    print(f"           → {OUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
