"""hapbeat-helper — local daemon bridging Studio (web) to Hapbeat devices."""

try:
    # Generated by scripts/gen_version.py (gitignored).
    # Present in local dev installs; absent in PyPI releases.
    from hapbeat_helper._version import __version__
except ImportError:
    # Fallback: release version embedded at publish time.
    # Keep this in sync with pyproject.toml [project] version.
    __version__ = "0.1.2"
